In [1]:
%pip install pandas numpy matplotlib seaborn openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.13/dist-packages (0.13.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (3.3.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
# Import the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 120)

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
# Load the dataset
df = pd.read_csv("Nassau Candy Distributor.csv")

print("Dataset loaded successfully!")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

display(df.head())

Dataset loaded successfully!
Number of rows: 10194
Number of columns: 18

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [4]:
# Understand the columns
print("Column names:")
print(df.columns.tolist())

print("\nDataset information:")
df.info()

print("\nFirst 10 records:")
display(df.head(10))

print("\nRandom 5 records:")
display(df.sample(5, random_state=42))

Column names:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name', 'Sales', 'Units', 'Gross Profit', 'Cost']

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), object(12)
memory usage: 1.4+ MB

First 10 records:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90
5,6,US-2021-167199-CHO-SCR-58000,06-01-2024,03-07-2026,Standard Class,167199,United States,Henderson,Kentucky,42420,Chocolate,Gulf,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,32.40,9,22.50,9.90
6,7,US-2021-167199-CHO-TRI-54000,06-01-2024,03-07-2026,Standard Class,167199,United States,Henderson,Kentucky,42420,Chocolate,Gulf,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
7,8,US-2021-106054-CHO-MIL-31000,06-01-2024,30-06-2026,First Class,106054,United States,Athens,Georgia,30605,Chocolate,Gulf,CHO-MIL-31000,Wonka Bar - Milk Chocolate,9.75,3,6.33,3.42
8,9,US-2021-167199-CHO-NUT-13000,06-01-2024,03-07-2026,Standard Class,167199,United States,Henderson,Kentucky,42420,Chocolate,Gulf,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,6.98,2,4.98,2.00
9,10,US-2021-167199-CHO-MIL-31000,06-01-2024,03-07-2026,Standard Class,167199,United States,Henderson,Kentucky,42420,Chocolate,Gulf,CHO-MIL-31000,Wonka Bar - Milk Chocolate,13.00,4,8.44,4.56

Random 5 records:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
6636,6637,US-2023-108777-CHO-FUD-51000,12-12-2025,03-06-2029,Same Day,108777,United States,Lorain,Ohio,44052,Chocolate,Atlantic,CHO-FUD-51000,Wonka Bar - Fudge Mallows,10.80,3,7.20,3.6
3742,3743,US-2022-102778-CHO-TRI-54000,21-11-2024,16-05-2028,First Class,102778,United States,Monroe,North Carolina,28110,Chocolate,Gulf,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,3.75,1,2.45,1.3
5114,5115,US-2023-153577-CHO-TRI-54000,27-06-2025,21-12-2028,Standard Class,153577,United States,Highland Park,Illinois,60035,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.9
6505,6506,US-2023-161025-CHO-FUD-51000,03-12-2025,31-05-2029,Standard Class,161025,United States,Los Angeles,California,90049,Chocolate,Pacific,CHO-FUD-51000,Wonka Bar - Fudge Mallows,14.40,4,9.60,4.8
10072,10073,US-2024-155376-CHO-SCR-58000,22-12-2025,19-06-2030,Standard Class,155376,United States,Independence,Missouri,64055,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.3

In [5]:
# Check missing values
missing_values = df.isnull().sum()

missing_report = pd.DataFrame({
    "Missing Count": missing_values,
    "Missing Percentage": (
        missing_values / len(df) * 100
    ).round(2)
})

display(missing_report)

                Missing Count  Missing Percentage
Row ID                      0                 0.0
Order ID                    0                 0.0
Order Date                  0                 0.0
Ship Date                   0                 0.0
Ship Mode                   0                 0.0
Customer ID                 0                 0.0
Country/Region              0                 0.0
City                        0                 0.0
State/Province              0                 0.0
Postal Code                 0                 0.0
Division                    0                 0.0
Region                      0                 0.0
Product ID                  0                 0.0
Product Name                0                 0.0
Sales                       0                 0.0
Units                       0                 0.0
Gross Profit                0                 0.0
Cost                        0                 0.0

In [6]:
# Check duplicate records
print("Exact duplicate rows:", df.duplicated().sum())

print("Duplicate Row IDs:", df["Row ID"].duplicated().sum())

print("Unique customers:", df["Customer ID"].nunique())

print("Unique orders:", df["Order ID"].nunique())

Exact duplicate rows: 0
Duplicate Row IDs: 0
Unique customers: 5044
Unique orders: 8549

In [7]:
# Check and convert data types
df_clean = df.copy()

df_clean["Order Date"] = pd.to_datetime(
    df_clean["Order Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

df_clean["Ship Date"] = pd.to_datetime(
    df_clean["Ship Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

print(df_clean[["Order Date", "Ship Date"]].dtypes)

display(df_clean[["Order Date", "Ship Date"]].head())

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

  Order Date  Ship Date
0 2024-01-03 2026-06-30
1 2024-01-04 2026-07-01
2 2024-01-04 2026-07-01
3 2024-01-04 2026-07-01
4 2024-01-05 2026-07-05

In [8]:
# Validate the dates
df_clean["Shipping Delay Days"] = (
    df_clean["Ship Date"] - df_clean["Order Date"]
).dt.days

print("Shipping delay summary:")
display(df_clean["Shipping Delay Days"].describe())

print("\nSample records with dates:")
display(
    df_clean[
        ["Order ID", "Order Date", "Ship Date",
         "Shipping Delay Days"]
    ].head(10)
)

Shipping delay summary:

count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Shipping Delay Days, dtype: float64

Sample records with dates:

                       Order ID Order Date  Ship Date  Shipping Delay Days
0  US-2021-103800-CHO-MIL-31000 2024-01-03 2026-06-30                  909
1  US-2021-112326-CHO-TRI-54000 2024-01-04 2026-07-01                  909
2  US-2021-112326-CHO-NUT-13000 2024-01-04 2026-07-01                  909
3  US-2021-112326-CHO-SCR-58000 2024-01-04 2026-07-01                  909
4  US-2021-141817-CHO-TRI-54000 2024-01-05 2026-07-05                  912
5  US-2021-167199-CHO-SCR-58000 2024-01-06 2026-07-03                  909
6  US-2021-167199-CHO-TRI-54000 2024-01-06 2026-07-03                  909
7  US-2021-106054-CHO-MIL-31000 2024-01-06 2026-06-30                  906
8  US-2021-167199-CHO-NUT-13000 2024-01-06 2026-07-03                  909
9  US-2021-167199-CHO-MIL-31000 2024-01-06 2026-07-03                  909

In [9]:
# Validate numerical columns
numeric_cols = [
    "Sales", "Units", "Gross Profit", "Cost"
]

print("Negative values in numerical columns:")

for col in numeric_cols:
    print(col, ":", (df_clean[col] < 0).sum())

print("\nSales and cost summary:")
display(df_clean[numeric_cols].describe())

Negative values in numerical columns:
Sales : 0
Units : 0
Gross Profit : 0
Cost : 0

Sales and cost summary:

              Sales         Units  Gross Profit          Cost
count  10194.000000  10194.000000  10194.000000  10194.000000
mean      13.908537      3.791838      9.166451      4.742087
std       11.341020      2.228317      6.643740      5.061647
min        1.250000      1.000000      0.250000      0.600000
25%        7.200000      2.000000      4.900000      2.400000
50%       10.800000      3.000000      7.470000      3.600000
75%       18.000000      5.000000     12.250000      5.700000
max      260.000000     14.000000    130.000000    130.000000

In [10]:
# Save the cleaned dataset
output_file = "Nassau_Candy_Cleaned.csv"

df_clean.to_csv(output_file, index=False)

print("Dataset saved as:", output_file)
print("Final shape:", df_clean.shape)

Dataset saved as: Nassau_Candy_Cleaned.csv
Final shape: (10194, 19)